name: On Push to Main Branch

on:
    push:
        branches:
            - main

jobs:
    main-branch-push:
        name: Main Push
        runs-on: ubuntu-24.04
        permissions:
          contents: write
        steps:
            - name: Checkout sources to make local actions available
              uses: actions/checkout@v4

            - name: Get the version value
              id: version
              uses: ./actions/artifact-version

            - name: Show outputs
              run: | 
                echo "value=${{steps.version.outputs.value}}"

            - name: Tag Repo
              uses: richardsimko/update-tag@v1.1.6
              with:
                tag_name: ${{steps.version.outputs.value}}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}